# 服务端口
server:
  port: 9899

# 服务名称
spring:
  application:
    name: zuul-gateway-service

# 网关配置
zuul:
  routes:
    provider-01:
      path: /getPro01/**
      serviceId: zuul-provider-01
    provider-02:
      path: /getPro02/**
      serviceId: zuul-provider-02

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9898/eureka/
